# ~/dotfiles/starship/.config/starship.toml
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[package]
disabled = true # Reduces clutter

[aws]
symbol = "â˜ï¸ "

[python]
symbol = "ğŸ "

[conda]
symbol = "ğŸ…’ "
format = "[$symbol$environment]($style) " # Removed "via" for a cleaner look
ignore_base = true # Hides the prompt if you are in the 'base' env
