# ~/dotfiles/starship/.config/starship.toml
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[package]
disabled = true # Reduces clutter

[aws]
symbol = "â˜ï¸ "

[python]
symbol = "ğŸ "
